### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ribb-nchan** [smark91/terraform-cloud-discord-webhook-proxy#3]
What's the license? This is a nice little project that fits exactly what I need but I just realized I forked before checking for one >_<

**Comment by smark91** [comment]
I decided to go for a [GPL-3.0 license](https://choosealicense.com/licenses/gpl-3.0/#)
https://github.com/smark91/terraform-cloud-discord-webhook-proxy/blob/main/LICENSE
